// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7kItoiNcSwQJg55XH_0-D23r5DFOL30',
    appId: '1:850624934951:web:07b64f9c6dff3aa2bf0a02',
    messagingSenderId: '850624934951',
    projectId: 'story-sprout-test-project',
    authDomain: 'story-sprout-test-project.firebaseapp.com',
    storageBucket: 'story-sprout-test-project.firebasestorage.app',
    measurementId: 'G-WQPPX1BHH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIaMX9R5NFm0V5ARG5B-UtI16A6ilZ6bQ',
    appId: '1:850624934951:android:66f04c5ae5feb45bbf0a02',
    messagingSenderId: '850624934951',
    projectId: 'story-sprout-test-project',
    storageBucket: 'story-sprout-test-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAfurzhXy4DjssV_nKSKMJWXf72T34E34',
    appId: '1:850624934951:ios:c442bd672f750b5cbf0a02',
    messagingSenderId: '850624934951',
    projectId: 'story-sprout-test-project',
    storageBucket: 'story-sprout-test-project.firebasestorage.app',
    iosBundleId: 'com.UNT.storysprout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAfurzhXy4DjssV_nKSKMJWXf72T34E34',
    appId: '1:850624934951:ios:c442bd672f750b5cbf0a02',
    messagingSenderId: '850624934951',
    projectId: 'story-sprout-test-project',
    storageBucket: 'story-sprout-test-project.firebasestorage.app',
    iosBundleId: 'com.UNT.storysprout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw7kItoiNcSwQJg55XH_0-D23r5DFOL30',
    appId: '1:850624934951:web:4e5c1d2ab6dd7bbabf0a02',
    messagingSenderId: '850624934951',
    projectId: 'story-sprout-test-project',
    authDomain: 'story-sprout-test-project.firebaseapp.com',
    storageBucket: 'story-sprout-test-project.firebasestorage.app',
    measurementId: 'G-QTRDFBZ915',
  );

}